### ISSUE TITLE
External Triggering

### ISSUE THREAD

**Issue by jwaterfield** [snoplus/tellie#7] opened 2013-09-20 13:17 UTC
Ensure full sequence ran before PIN is read out.

Work out what to do about run boundaries

**Comment by mnirkko** [comment] 2017-10-26 17:36
Possible duplicate of Issue #9 - probably fixed. "Run boundaries" is vague and needs further clarification.
Suggest closing.

**Closed as completed** 2020-01-29 16:06 UTC
Labels: enhancement
